### PR TITLE
WIP: Toolbar for adding components to the map

### PR DESCRIPTION
**Pull request by ChristianDavis**
Hey @damonsk, thanks for putting this tool together, I love it! Would you be interested in added some buttons to a toolbar? This is a real rough example but seems promising. Toolbar slides out, contains the functionality of the usages section. 

If you're interested we can talk about how you want it to work & look.

toolbar_screencap

### CODE REVIEW

**Comment by damonsk** [comment]
Thanks @ChristianDavis!

Had a quick look and play and it is what I had in mind with Issue #61 

As I looked and played - it would be nice if we could leverage the icons from here and it would be perfect as we add more of the missing elements.

Symbols used in Wardley Maps

I'd be happy to merge in when you feel its in a good place and contribute myself if needed.

Many thanks

**Comment by ChristianDavis** [comment]
Dope! Yeah I initially was drawing the icons, that way it preserves the styling, but it requires a little refactoring to lift up the symbols. Do you want to go that route?

**Comment by damonsk** [comment]
Yeah I think so - drawing and preserving the styling seems like the way to go.  Thanks

**Comment by ChristianDavis** [comment]
was thinking something like this:
Screen Shot 2020-04-28 at 12 10 08 PM

But regardless of the toolbar/icon design, splitting the symbols out starts giving a nice separation of concerns between a component and the symbol. e.g. MapComponent cares about elements, ids, position, symbol just wants styles

**Comment by damonsk** [comment]
This is looking good and I like the separation you've introduced.  It feel like it could open up the opportunity to drive the map creation more from the toolbar over writing text.  Like toggling the WYSIWG toolbar over writing pure code. 

Just one thing I noticed - the symbol on a component with a pipeline has revered to a circle rather square.    

```
component Customer [0.9, 0.5]
pipeline Customer [0,1, 0.3]
```

**Comment by ChristianDavis** [comment]
my bad, imported the wrong symbol

**Comment by ChristianDavis** [comment]
If you'd like to play with the changes and think about the design you'd like I'll just convert some of the symbols. When you know what direction you wanna go in I'll knock it out

**Comment by ChristianDavis** [comment]
BTW, the text editor is dope. You get a lot out of it, the only thing I'd change is adding some more formal parsing under the hood so you can do quick lookups, handle token collisions, display some syntax issues, etc.

**Comment by damonsk** [comment]
I think finish the rest of in the same approach - taking style from the map, we can merge in and then start tweaking it, building on it more - some ideas - available styles could be a dropdown of all styles.

**Pull request closed without merging**
